import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/component/provider/ThemeProvider";
import ThemeButton from "@/component/button/ThemeButton";
import NavigationLayout from "@/component/layout/NavigationLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavigationLayout />
          <ThemeButton />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
